# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pill_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import QCoreApplication
import pymysql
import os

class Ui_MainWindow(object):
    def __init__(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.con = pymysql.connect(host='localhost', user='raspi', password='1234', db='pill_db', charset='utf8')
        self.cur = self.con.cursor()
        self.num = 0
        self.name = 'None'
        self.time = 'None'
        self.info = 'None'
        self.img_label = QtWidgets.QLabel(MainWindow)
        self.img_label.setGeometry(QtCore.QRect(30, 450, 500, 230))
        self.img_label.setAcceptDrops(False)
        self.img_label.setAutoFillBackground(False)
        self.img_label.setMidLineWidth(0)
        self.img_label.setText("")
        self.img_label.setObjectName("img_label")
        self.img_pix = QPixmap()
        self.img_list_group = QtWidgets.QGroupBox(MainWindow)
        self.img_list_group.setGeometry(QtCore.QRect(20, 20, 1160, 400))
        self.img_list_group.setTitle("")
        self.img_list_group.setObjectName("img_list_group")
        self.img = [QtWidgets.QLabel(self.img_list_group),QtWidgets.QLabel(self.img_list_group),QtWidgets.QLabel(self.img_list_group),QtWidgets.QLabel(self.img_list_group),QtWidgets.QLabel(self.img_list_group),QtWidgets.QLabel(self.img_list_group),QtWidgets.QLabel(self.img_list_group),QtWidgets.QLabel(self.img_list_group),QtWidgets.QLabel(self.img_list_group),QtWidgets.QLabel(self.img_list_group)]
        self.img[0].setGeometry(QtCore.QRect(0, 0, 210, 180))
        self.img[0].setAcceptDrops(False)
        self.img[0].setAutoFillBackground(False)
        self.img[0].setStyleSheet("color: #4D69E8; border-style: solid; border-width: 2px; border-color: #BBBBBB; border-radius: 10px;")
        self.img[0].setMidLineWidth(0)
        self.img[1].setGeometry(QtCore.QRect(240, 0, 210, 180))
        self.img[1].setAcceptDrops(False)
        self.img[1].setAutoFillBackground(False)
        self.img[1].setStyleSheet("color: #4D69E8; border-style: solid; border-width: 2px; border-color: #BBBBBB; border-radius: 10px;")
        self.img[1].setMidLineWidth(0)
        self.img[2].setGeometry(QtCore.QRect(470, 0, 210, 180))
        self.img[2].setAcceptDrops(False)
        self.img[2].setAutoFillBackground(False)
        self.img[2].setStyleSheet("color: #4D69E8; border-style: solid; border-width: 2px; border-color: #BBBBBB; border-radius: 10px;")
        self.img[2].setMidLineWidth(0)
        self.img[3].setGeometry(QtCore.QRect(700, 0, 210, 180))
        self.img[3].setAcceptDrops(False)
        self.img[3].setAutoFillBackground(False)
        self.img[3].setStyleSheet("color: #4D69E8; border-style: solid; border-width: 2px; border-color: #BBBBBB; border-radius: 10px;")
        self.img[3].setMidLineWidth(0)
        self.img[4].setGeometry(QtCore.QRect(930, 0, 210, 180))
        self.img[4].setAcceptDrops(False)
        self.img[4].setAutoFillBackground(False)
        self.img[4].setStyleSheet("color: #4D69E8; border-style: solid; border-width: 2px; border-color: #BBBBBB; border-radius: 10px;")
        self.img[4].setMidLineWidth(0)
        self.img[5].setGeometry(QtCore.QRect(0, 210, 210, 180))
        self.img[5].setAcceptDrops(False)
        self.img[5].setAutoFillBackground(False)
        self.img[5].setStyleSheet("color: #4D69E8; border-style: solid; border-width: 2px; border-color: #BBBBBB; border-radius: 10px;")
        self.img[5].setMidLineWidth(0)
        self.img[6].setGeometry(QtCore.QRect(240, 210, 210, 180))
        self.img[6].setAcceptDrops(False)
        self.img[6].setAutoFillBackground(False)
        self.img[6].setStyleSheet("color: #4D69E8; border-style: solid; border-width: 2px; border-color: #BBBBBB; border-radius: 10px;")
        self.img[6].setMidLineWidth(0)
        self.img[7].setGeometry(QtCore.QRect(470, 210, 210, 180))
        self.img[7].setAcceptDrops(False)
        self.img[7].setAutoFillBackground(False)
        self.img[7].setStyleSheet("color: #4D69E8; border-style: solid; border-width: 2px; border-color: #BBBBBB; border-radius: 10px;")
        self.img[7].setMidLineWidth(0)
        self.img[8].setGeometry(QtCore.QRect(700, 210, 210, 180))
        self.img[8].setAcceptDrops(False)
        self.img[8].setAutoFillBackground(False)
        self.img[8].setStyleSheet("color: #4D69E8; border-style: solid; border-width: 2px; border-color: #BBBBBB; border-radius: 10px;")
        self.img[8].setMidLineWidth(0)
        self.img[9].setGeometry(QtCore.QRect(930, 210, 210, 180))
        self.img[9].setAcceptDrops(False)
        self.img[9].setAutoFillBackground(False)
        self.img[9].setStyleSheet("color: #4D69E8; border-style: solid; border-width: 2px; border-color: #BBBBBB; border-radius: 10px;")
        self.img[9].setMidLineWidth(0)
        self.btn_ok = QtWidgets.QPushButton(MainWindow)
        self.btn_ok.setGeometry(QtCore.QRect(1000, 690, 140, 61))
        self.btn_ok.setStyleSheet("background-color : #BBBBBB;")
        self.btn_ok.clicked.connect(QCoreApplication.instance().quit)
        self.btn_del = QtWidgets.QPushButton(MainWindow)
        self.btn_del.setGeometry(QtCore.QRect(850, 690, 140, 61))
        self.btn_del.setStyleSheet("background-color : #BBBBBB;")
        self.btn_ch = QtWidgets.QPushButton(MainWindow)
        self.btn_ch.setGeometry(QtCore.QRect(700, 690, 140, 61))
        self.btn_ch.setStyleSheet("background-color : #BBBBBB;")
        self.pill_name = QtWidgets.QGroupBox(MainWindow)
        self.pill_name.setGeometry(QtCore.QRect(40, 690, 480, 60))
        self.pill_name.setStyleSheet("border-style: dashed; border-width: 1px; border-color: gray;")
        self.pill_name.setTitle("")
        self.pill_name.setObjectName("pill_name")
        self.sub_name = QtWidgets.QLabel(self.pill_name)
        self.sub_name.setGeometry(QtCore.QRect(0, 0, 101, 60))
        self.sub_name.setTextFormat(QtCore.Qt.AutoText)
        self.sub_name.setObjectName("sub_name")
        self.cont_name = QtWidgets.QLabel(self.pill_name)
        self.cont_name.setGeometry(QtCore.QRect(100, 0, 380, 60))
        self.cont_name.setObjectName("cont_name")
        self.pill_time = QtWidgets.QGroupBox(MainWindow)
        self.pill_time.setGeometry(QtCore.QRect(550, 460, 600, 50))
        self.pill_time.setStyleSheet("border-style: dashed; border-width: 2px; border-color: gray;")
        self.pill_time.setTitle("")
        self.pill_time.setObjectName("pill_time")
        self.sub_time = QtWidgets.QLabel(self.pill_time)
        self.sub_time.setGeometry(QtCore.QRect(0, 0, 120, 50))
        self.sub_time.setObjectName("sub_time")
        self.cont_time = QtWidgets.QLabel(self.pill_time)
        self.cont_time.setGeometry(QtCore.QRect(120, 0, 500, 50))
        self.cont_time.setObjectName("cont_time")
        self.pill_info = QtWidgets.QGroupBox(MainWindow)
        self.pill_info.setGeometry(QtCore.QRect(550, 530, 600, 120))
        self.pill_info.setStyleSheet("border-style: dashed; border-width: 2px; border-color: gray;")
        self.pill_info.setObjectName("pill_info")
        self.sub_info = QtWidgets.QLabel(self.pill_info)
        self.sub_info.setGeometry(QtCore.QRect(0, 0, 120, 120))
        self.sub_info.setObjectName("sub_info")
        self.cont_info = QtWidgets.QLabel(self.pill_info)
        self.cont_info.setGeometry(QtCore.QRect(120, 0, 480, 120))
        self.cont_info.setObjectName("cont_info")
        self.btn_pre = QtWidgets.QPushButton(MainWindow)
        self.btn_pre.setGeometry(QtCore.QRect(500, 420, 89, 25))
        self.btn_pre.setObjectName("btn_pre")
        self.btn_next = QtWidgets.QPushButton(MainWindow)
        self.btn_next.setGeometry(QtCore.QRect(600, 420, 89, 25))
        self.btn_next.setObjectName("btn_next")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_ok.setText(_translate("MainWindow", "OK"))
        self.btn_del.setText(_translate("MainWindow", "DELETE"))
        self.btn_ch.setText(_translate("MainWindow", "Change"))
        self.sub_name.setText(_translate("MainWindow", "약품 이름"))
        self.sub_time.setText(_translate("MainWindow", "복용 시간"))
        self.sub_info.setText(_translate("MainWindow", "복용 정보"))
        self.btn_pre.setText(_translate("MainWindow", "◀"))
        self.btn_next.setText(_translate("MainWindow", "▶"))
        self.img_label.setPixmap(self.img_pix)

    def show_ui(self, i, num):
        sql = "select num, name, time, efficacy from pill where num = \'" + str(num) + "\';"

        self.cur.execute(sql)
        data = self.cur.fetchall()
        data = list(data[0])

        self.cont_name.setText(data[1])
        self.cont_time.setText(data[2])
        self.cont_info.setText(data[3])

        ch_img_pix = QtGui.QPixmap('./pill_image/' + str(data[0]) + '.jpg')
        self.img_label.setPixmap(ch_img_pix)
        dir_path = './image/' + str(i).zfill(2) + '/'
        data_count = os.listdir(dir_path)

        for i in range(len(data_count)):
            self.img[i].setPixmap(QtGui.QPixmap(dir_path+data_count[i]))
