# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage, QPalette, QBrush
import rot1_ui, rot2_ui, rot3_ui, rot4_ui
import test1, test2, test3, test4

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        super().__init__()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        img = QImage('background_ui.png')
        p = QPalette()
        p.setBrush(10, QBrush(img))
        MainWindow.setPalette(p)
        #self.centralwidget = QtWidgets.QWidget(MainWindow)
        #self.centralwidget.setObjectName("centralwidget")
        self.rot1 = QtWidgets.QPushButton(MainWindow)
        self.rot1.setGeometry(QtCore.QRect(480, 280, 50, 50))
        self.rot1.setObjectName("rot1")
        self.rot1.setStyleSheet("color: white; background-color: #3a86ff; border-radius: 20px;")
        self.rot1.clicked.connect(self.show_rot1)
        self.rot2 = QtWidgets.QPushButton(MainWindow)
        self.rot2.setGeometry(QtCore.QRect(670, 280, 50, 50))
        self.rot2.setObjectName("rot2")
        self.rot2.setStyleSheet("color: white; background-color: #3a86ff; border-radius: 20px;")
        self.rot2.clicked.connect(self.show_rot2)
        self.rot3 = QtWidgets.QPushButton(MainWindow)
        self.rot3.setGeometry(QtCore.QRect(480, 480, 50, 50))
        self.rot3.setObjectName("rot3")
        self.rot3.setStyleSheet("color: white; background-color: #3a86ff; border-radius: 20px;")
        self.rot3.clicked.connect(self.show_rot3)
        self.rot4 = QtWidgets.QPushButton(MainWindow)
        self.rot4.setGeometry(QtCore.QRect(670, 480, 50, 50))
        self.rot4.setObjectName("rot4")
        self.rot4.setStyleSheet("color: white; background-color: #3a86ff; border-radius: 20px;")
        self.rot4.clicked.connect(self.show_rot4)
        self.pushButton = QtWidgets.QPushButton(MainWindow)
        self.pushButton.setGeometry(QtCore.QRect(555, 370, 100, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(555, 410, 100, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rot1.setText(_translate("MainWindow", "1"))
        self.rot2.setText(_translate("MainWindow", "2"))
        self.rot3.setText(_translate("MainWindow", "3"))
        self.rot4.setText(_translate("MainWindow", "4"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop"))

    def show_rot1(self):
        self.MainD = QtWidgets.QDialog()
        self.rot = test1.test1_ui(self.MainD)
        self.MainD.show()

    def show_rot2(self):
        self.MainD = QtWidgets.QDialog()
        self.rot = test2.test2_ui(self.MainD)
        self.MainD.show()

    def show_rot3(self):
        self.MainD = QtWidgets.QDialog()
        self.rot = test3.test3_ui(self.MainD)
        self.MainD.show()

    def show_rot4(self):
        self.MainD = QtWidgets.QDialog()
        self.rot = test4.test4_ui(self.MainD)
        self.MainD.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
