# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rot1_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl1.setGeometry(QtCore.QRect(680, 10, 100, 100))
        self.lbl1.setStyleSheet("border-style: solid; border-width: 10px; border-color: #666666; border-radius: 50px;")
        self.lbl1.setObjectName("lbl1")
        self.lbl2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl2.setGeometry(QtCore.QRect(570, 50, 100, 100))
        self.lbl2.setStyleSheet("border-style: solid; border-width: 10px; border-color: #666666; border-radius: 50px;")
        self.lbl2.setObjectName("lbl2")
        self.lbl3 = QtWidgets.QLabel(self.centralwidget)
        self.lbl3.setGeometry(QtCore.QRect(470, 110, 100, 100))
        self.lbl3.setStyleSheet("border-style: solid; border-width: 10px; border-color: #666666; border-radius: 50px;")
        self.lbl3.setObjectName("lbl3")
        self.lbl4 = QtWidgets.QLabel(self.centralwidget)
        self.lbl4.setGeometry(QtCore.QRect(380, 180, 100, 100))
        self.lbl4.setStyleSheet("border-style: solid; border-width: 10px; border-color: #666666; border-radius: 50px;")
        self.lbl4.setObjectName("lbl4")
        self.lbl5 = QtWidgets.QLabel(self.centralwidget)
        self.lbl5.setGeometry(QtCore.QRect(290, 250, 100, 100))
        self.lbl5.setStyleSheet("border-style: solid; border-width: 10px; border-color: #666666; border-radius: 50px;")
        self.lbl5.setObjectName("lbl5")
        self.lbl6 = QtWidgets.QLabel(self.centralwidget)
        self.lbl6.setGeometry(QtCore.QRect(210, 330, 100, 100))
        self.lbl6.setStyleSheet("border-style: solid; border-width: 10px; border-color: #666666; border-radius: 50px;")
        self.lbl6.setObjectName("lbl6")
        self.lbl7 = QtWidgets.QLabel(self.centralwidget)
        self.lbl7.setGeometry(QtCore.QRect(140, 420, 100, 100))
        self.lbl7.setStyleSheet("border-style: solid; border-width: 10px; border-color: #666666; border-radius: 50px;")
        self.lbl7.setObjectName("lbl7")
        self.lbl8 = QtWidgets.QLabel(self.centralwidget)
        self.lbl8.setGeometry(QtCore.QRect(70, 510, 100, 100))
        self.lbl8.setStyleSheet("border-style: solid; border-width: 10px; border-color: #666666; border-radius: 50px;")
        self.lbl8.setObjectName("lbl8")
        self.lbl9 = QtWidgets.QLabel(self.centralwidget)
        self.lbl9.setGeometry(QtCore.QRect(10, 610, 100, 100))
        self.lbl9.setStyleSheet("border-style: solid; border-width: 10px; border-color: #666666; border-radius: 50px;")
        self.lbl9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl9.setObjectName("lbl9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl1.setText(_translate("MainWindow", "1"))
        self.lbl2.setText(_translate("MainWindow", "2"))
        self.lbl3.setText(_translate("MainWindow", "3"))
        self.lbl4.setText(_translate("MainWindow", "4"))
        self.lbl5.setText(_translate("MainWindow", "5"))
        self.lbl6.setText(_translate("MainWindow", "6"))
        self.lbl7.setText(_translate("MainWindow", "7"))
        self.lbl8.setText(_translate("MainWindow", "8"))
        self.lbl9.setText(_translate("MainWindow", "9"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
